### ISSUE TITLE
Implement an EMF im- and export facility

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#119]

**Comment by enikao** [comment]
Does this make sense to re-implement in TS? If someone uses EMF, they are most likely in a Java environment, and then could use the Java LW-ECore bridge.

**Comment by dslmeinte** [comment]
Good point! But then I'd also like to be able to use the Java implementation more easily, e.g. as a CLI. I'll make an issue {i|o}n the Java repo.
