### ISSUE TITLE
Provide some statistics for serialization chunks (also as CLI)

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#120]
Statistics/metrics:

- which concepts are used (how often, and with backreferences?)
- number of nodes
- number of references (targets)
- etc.

Functional “design”:

Provide a CLI command (as part of `@lionweb/cli`) `measure` (to keep it a verb, like textualize, etc.). This command takes any number of paths to serialization chunks. All paths coming after a `--language` or `--languages` flag are loaded as languages, and are not measured. Every other path is a “non-language path” and is measured, resulting in a `<file name>.metrics.json` file. This metrics JSON file is again a serialization chunk, adhering to a language we have to define as part of this feature.

Technically:

The actual calculation of the metrics should happen in a function in the `utilities` package.

**Comment by dslmeinte** [comment]
> What do you mean with keeping "language defs" in one package?

If we render the metrics as an instance of a separate language, we need a definition for that language somewhere. But let's see what we run into while implementing this feature before pulling it into a separate package.

**Comment by joswarmer** [comment]
Ok, I understand.

**Comment by dslmeinte** [comment]
Done per PR #140
