### ISSUE TITLE
Remove support for EMF (to delegate to Java)?

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#121]

**Comment by ftomassetti** [comment]
I am not familiar with the support to EMF in this particular project, but we have used EMF from Typescript in https://github.com/Strumenta/tylasu it has required a good amount of workarounds and caused a few headaches, so having support for EMF in only from Java, could save quite some effort, in my opinion

**Comment by dslmeinte** [comment]
And that's exactly why I created https://github.com/LionWeb-io/lionweb-java/issues/124. It's a good datapoint to hear that EMF is problematic in TypeScript space.
