### ISSUE TITLE
Add badges (especially for NPM releases) to the documentation

### ISSUE THREAD

**Issue by alessiostalla** [LionWeb-io/lionweb-typescript#135]
It would be useful for adoption if we had a version published, even if it's a development version with known and unknown bugs.

**Comment by dslmeinte** [comment]
We publish a beta version quite often. (See all versions via https://www.npmjs.com/org/lionweb)

Do you require a beta-release for a specific feature that's not in an official release yet?

**Comment by joswarmer** [comment]
Maybe we should release a standalone executable, that is much easier for people not familiar with the JS ecosystem and nodejs.

**Comment by dslmeinte** [comment]
> Maybe we should release a standalone executable, that is much easier for people not familiar with the JS ecosystem and nodejs.

Agreed, and even though `npx @lionweb/cli <command>` is a lot of work, it does rely on NPM (so Node.js).

That was the great thing about implementing this in Deno instead of Node.js: Deno can generate executables out-of-the-box.

[pkg](https://www.npmjs.com/package/pkg) might be something to check out.

**Comment by joswarmer** [comment]
pkg has been deprecated.  But there are several other we might use. Or move to node 21, since then it is native functionality in nodejs.

**Comment by joswarmer** [comment]
> I just saw that no releases are listed and no npm badge is present, so I wrongly assumed that no published version exists.

So we should fix this and list the releases and add an npm badge.

**Comment by alessiostalla** [comment]
It's a one-liner in the `Readme.md` file for each published package; the following Markdown

```
[![NPM Version](https://img.shields.io/npm/v/%40lionweb%2Fcore?label=%40lionweb%2Fcore)
](https://www.npmjs.com/package/@lionweb/core)
```

produces this: [![NPM Version](https://img.shields.io/npm/v/%40lionweb%2Fcore?label=%40lionweb%2Fcore)
](https://www.npmjs.com/package/@lionweb/core)

I've generated the above with the online tool at https://shields.io/badges/npm-version and then made it into a link to the published package. Once you've generated it, you don't have to change it for newer versions (unless you add or remove a package, or rename a package).

**Comment by dslmeinte** [comment]
Added a couple of badges here: https://github.com/LionWeb-io/lionweb-typescript/tree/feature/badges
I'd like to add a badge for the GitHub Action `test.yaml` but haven't succeeded so far.

**Comment by dslmeinte** [comment]
This might help: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

**Comment by dslmeinte** [comment]
Oh, wait: already did the GitHub Action badge. Closing this issue.
