### ISSUE TITLE
Infer (partial) language definition from chunk

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#137]
Infer `Language`s from a given `SerializationChunk`. Obviously, the result is partial (no inheritance data etc.), but could serve as a starting point.

**Comment by joswarmer** [comment]
I would rename this issue to something like "Infer (partial) language definition from chunk. Reconstitute is much more that this.

**Comment by dslmeinte** [comment]
Implemented by @ahmed-negm in PR #141
