### ISSUE TITLE
classBasedClassifierDeducerFor doesn't work with bundlers/minifiers

### ISSUE THREAD

**Issue by alessiostalla** [LionWeb-io/lionweb-typescript#143]
`classBasedClassifierDeducerFor` uses the `constructor.name` property that bundlers and minifiers will potentially change. I managed to break it just by importing an unrelated "Property" function; the bundler decided to rename Lionweb's Property class to Property2, thus making it impossible to deserialize any language.

In Tylasu we solved this with an optional property one can add to classes to fix their name, and a decorator that makes setting the property easier. Something like:

```typescript
@Classifier("Property")
export class Property {
  ...
}
```

**Comment by dslmeinte** [comment]
The easiest way to fix this is probably to add a field `metaType` to the abstract class `M3Node` and populate that with the correct string.

**Comment by dslmeinte** [comment]
See PR #146

**Comment by dslmeinte** [comment]
Fixed by PR #146
