### ISSUE TITLE
Support deserialization of sub-trees and not just entire partitions

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-typescript#145]
I think this should be changed to support deserializing subtrees:

https://github.com/LionWeb-io/lionweb-typescript/blob/8e6b058c38fe8b8eb5942c7702122eba613bf826/packages/core/src/deserializer.ts#L48

We recently encountered the very same problem in lioncore-java where we had the same logic. The problem is that in this way we are only able to deserialize entire partitions, but nothing below them. 

See https://github.com/LionWeb-io/lionweb-java/pull/132 for comparison

**Comment by dslmeinte** [comment]
So, we should

- Construct nodes from all serialized nodes
- Resolve references
- Return those nodes that have parent `null` or an unresolvable parent

?

**Comment by ftomassetti** [comment]
Yes, I would do that.
In Java we can define the three options:
* Throw exception if there is any parent we cannot solve (but that means that either we ask only for entire partitions or we have another mechanism to solve nodes, for example because we already have on the client side)
* Set them to null
* Use sort of purely working proxies

Of these, I think that the only option that makes sense in most cases is setting the parent to null

**Comment by dslmeinte** [comment]
At this point, I wouldn't really do anything too configurable in the TS-space, so I'd simply set things to `null`.

**Comment by dslmeinte** [comment]
Fixed by PR #148
