### ISSUE TITLE
Implement reference utils

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#165]
Like done for C#:

- `referencesTo(...nodes: Node[])`: computes and returns all references coming into the given nodes, as a value of a simple structure mentioning both source and target of the reference, which `Reference` (on the source's `Classifier`) and (if the reference is multi-valued) the index.

**Comment by joswarmer** [comment]
Not sure I understand :-), don't know C# solution

**Comment by dslmeinte** [comment]
See PR #180
