### ISSUE TITLE
[delta protocol] moving a child between parents, replacing a child at the destination

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#188]
Suppose you have the following situation:

1. Nodes `child1`, `child2`
2. Nodes `parent1`, `parent2`, having containments `value1`, `value2`, both having a type that encompasses `child1` and `child2`. `value1` must be 0..1, `value2` can be either 0..1 or 1.
3. `parent1.value1 = child1`, and `parent2.value2 = child2`

Then `parent2.value2 = child1` is executed. This means that `child1` is not only moved from `parent1` to `parent2` but it also replaces `child2`. There's currently no command/event combination that covers that atomically: the “replace child” pair covers replacing a(n existing) child in a parent with another child, but that doesn't cover moving the new child from another source — it essentially assumed that the new child isn't contained by a parent yet.

We could emit two commands/events (as part of a composite, probably) but then we still have to define which two exactly (and in which order?).

**Comment by enikao** [comment]
Should this issue be here or in specification repo?

**Comment by dslmeinte** [comment]
> Should this issue be here or in specification repo?

In the specification repo... For some reason – tiredness, probably – I put it here. Will fix tomorrow.

**Comment by dslmeinte** [comment]
In wrong repo. Correct one: https://github.com/LionWeb-io/specification/issues/321
