### ISSUE TITLE
Export Node interface

### ISSUE THREAD

**Issue by alessiostalla** [LionWeb-io/lionweb-typescript#47]
Is `Node` meant to be implemented by LionCore-compatible libraries such as Tylasu? Right now, it's not exported, so we cannot make a Tylasu node "be-a" LionCore node.

**Comment by dslmeinte** [comment]
`Node` in `src/types.ts` is `export`-ed. A central `mod.ts` is lacking, so nothing is discoverable. Would a `mod.ts` suffice?
