### ISSUE TITLE
Multi-package repo

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#68]
Turn this (mono-)repo into a multi-package repo. That gives a lot more flexibility and ensures that we can provide TypeScript implementations of various aspects of LionWeb in a lean way (with as few dependencies per aspect as possible).

These packages should be NPM-packages that are scoped under [the `lionweb` organization]( https://www.npmjs.com/org/lionweb).

Possible packages:

- `core`: LionCore and base types
- `serialization`: everything regarding (de-)serialization
- `validation`: Jos' work on validators of serialization chunks
- `utilities`
- `cli`
- `test`: tests - not to be published on NPM!

Look at Freon4Dsl does this, e.g. using [workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) and [Verdaccio](https://verdaccio.org/) to not have to use `npm link` (and burn yourself).

This setup also implicitly whether using these packages works because ultimately `test` relies on most of the others.

**Comment by woppa684** [comment]
I would definitely not go for something like Verdaccio, that is not needed. In our company we're moving into [Nx](https://nx.dev/getting-started/intro), which also fulfills these needs. To just have multiple packages in a repo and let them reference each other, the only thing you basically need is to reference the path to the other packages in the tsconfig file.

**Comment by dslmeinte** [comment]
I might try out both, at least to gain some understanding of both, and then pick one. Until then, `npm link` kind-of works, as long as you don't forget to fix references before publishing.

**Comment by dslmeinte** [comment]
And maybe contents of `src/utils` of `core` &rarr; a separate package `base`?

**Comment by joswarmer** [comment]
I have been using verdaccio only for testing releases with clients that are outside the mono repo. Nx seems to be something different, providing a complete local build system for managing a mono repo. It looks like they are complementary to each other.

**Comment by woppa684** [comment]
That's correct indeed. Like I said, the only thing you need is to reference the local packages to be able to work with multiple packages in a single repo (no external tools whatsoever). Even that can be done in different ways. For example, either by referring to them in the package.json or by providing the correct paths in a tsconfig file.

**Comment by dslmeinte** [comment]
I still have some trouble with getting everything working in a development situation in which you want to point to the local version of packages, so I'm leaving this issue open for now.

**Comment by dslmeinte** [comment]
I solved that in the meanwhile in the sense that the pointing works, and doesn't pose a risk for accidentally publishing packages with `"file:../"`-type versions for deps.

Splitting of (de-)serialization is something that I'm not entirely sure about, still, so I'll leave on the Implicit Backlog ;)
