### ISSUE TITLE
Propagate existence of annotations

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/lionweb-typescript#75]
See also https://github.com/LionWeb-org/organization/issues/184
This also means e.g. that lots of occurrences of the `Concept` type should be replaced with the `Classifier` type, as well as `conceptOf` &rarr; `classifierOf`. (But isn't a `Classifier` a broader thing than a `Concept`? Are all `Classifier` instances instantiable?)

**Comment by enikao** [comment]
> But isn't a `Classifier` a broader thing than a `Concept`? Are all `Classifier` instances instantiable?

No, but that was also not the case before (abstract concepts).

**Comment by dslmeinte** [comment]
Done on `main`line, per commit [1ab76d8](https://github.com/LionWeb-io/lionweb-typescript/commit/1ab76d83c5a2617eed63297a245662bcc824c189).
